// frontend_v2/src/components/Notice.vue
<template lang="">
    <div class="Notice">
        <div class="headline">
            <h2 class="headline-title">공지사항</h2>
        </div>

        <div>
            <div class="board-list">
                <div class="important" v-for="(item, id) in importantList.results" :key="id">
                    <router-link id=board-router :to="`/notice/${item.id}`">
                        <span class="board-id">{{item.id}}</span>
                        <span class="board-title">{{item.title}}</span>
                        <span class="board-date">{{item.date}}</span>
                    </router-link>
                </div>
                <div v-for="(item, id) in boardList.results" :key="id">
                    <router-link id=board-router :to="`/notice/${item.id}`">
                        <span class="board-id">{{item.id}}</span>
                        <span class="board-title">{{item.title}}</span>
                        <span class="board-date">{{item.date}}</span>
                    </router-link>
                </div>
            </div>
            <b-pagination
                :total-rows="boardList.count"
                :per-page="15"
                align="center"
                @page-click="reTable"
            />

        </div>
    </div>
</template>
<script>
export default {
    name: 'Notice',
    components: {

    },
    data(){
        // 추후에는 axios이용해서 클릭했을 경우 각각의 데이터를 불러오도록 만들 예정
        return {
            currentPage:1,
            boardList:{
                count : 4,
                next : null,
                previous : null,
                results:[
                    {
                        id: 1,
                        title: "타이틀1",
                        contents: "컨텐츠!@!@",
                        date: "2021.03.07",
                    },
                    {
                        id: 2,
                        title: "타이틀2",
                        contents: "컨텐츠!@!@",
                        date: "2021.03.08",
                    },
                    {
                        id: 3,
                        title: "타이틀3",
                        contents: "컨텐츠!@!@",
                        date: "2021.03.09",
                    },
                    {
                        id: 4,
                        title: "타이틀4",
                        contents: "컨텐츠!@!@",
                        date: "2021.03.10",
                    },
                ]
            },
            importantList:{
                count : 4,
                next : null,
                previous : null,
                results:[
                    {
                        id: 1,
                        title: "타이틀1",
                        contents: "컨텐츠!@!@",
                        date: "2021.03.07",
                    },
                    {
                        id: 2,
                        title: "타이틀2",
                        contents: "컨텐츠!@!@",
                        date: "2021.03.08",
                    },
                    {
                        id: 3,
                        title: "타이틀3",
                        contents: "컨텐츠!@!@",
                        date: "2021.03.09",
                    },
                    {
                        id: 4,
                        title: "타이틀4",
                        contents: "컨텐츠!@!@",
                        date: "2021.03.10",
                    },
                ]
            },
        }
    },
    mounted(){
        this.init()
    },
    methods: {
        init(){
            this.getNotice()
            this.getImportant()
        },
        reTable : function(b,p){
            this.currentPage=p;
            this.getNotice();
        },
        getNotice(){
            this.axios
            .get('http://localhost:8000/notice/?page='+this.currentPage)
            .then(response => {
                console.log(response)
                this.boardList = response.data
            });
        },
        getImportant(){
            this.axios
            .get('http://localhost:8000/notice/important/')
            .then(response => {
                console.log(response)
                this.importantList = response.data
            });

        }

    },
}
</script>
<style scoped>
.headline-title {
    font-weight: 700;
    max-width: 1080px;
    margin: 0 auto;
    text-align: center;
    padding-bottom: 20px;
}
.important{
    background-color: gray;
}
.board-list{
    display: table;
    width: 1080px;
    border-top: 1px solid black;
    table-layout: fixed;
    margin: 0 auto;
}

#board-router{
    display: table-row;
    height: 60px;
}

.board-id, .board-data{
    text-align: middle;
    display: table-cell;
}

.board-id, .board-title, .board-date{
    vertical-align: middle;
    display: table-cell;
    padding-right: 30px;
    padding-left: 30px;
    box-sizing: border-box;
}
.board-id{
    width: 97px;
}

.board-title{
    text-overflow: ellipsis;
    white-space: nowrap;
    word-break: break-all;
    overflow: hidden;
    width: 100%;
}

.board-date{
    width: 125px;
}

a{
    color: black;
    text-decoration: none;
    font-size: 120%;
}
</style>

// frontend_react/src/components/Notice.js
import {Component} from "react";
import axios from 'axios';
import Pagination from './Pagination'
import "../css/Notice.css"

class Notice extends Component{
    state={
        currentPage:1,
        perPage:15,
        boardList:{
            count : 4,
            next : null,
            previous : null,
            results:[
                {
                    id: 1,
                    title: "타이틀1",
                    contents: "컨텐츠!@!@",
                    date: "2021.03.07",
                },
                {
                    id: 2,
                    title: "타이틀2",
                    contents: "컨텐츠!@!@",
                    date: "2021.03.08",
                },
                {
                    id: 3,
                    title: "타이틀3",
                    contents: "컨텐츠!@!@",
                    date: "2021.03.09",
                },
                {
                    id: 4,
                    title: "타이틀4",
                    contents: "컨텐츠!@!@",
                    date: "2021.03.10",
                },
            ]
        },
        importantList:[
                {
                    id: 1,
                    title: "타이틀1",
                    contents: "컨텐츠!@!@",
                    date: "2021.03.07",
                },
                {
                    id: 2,
                    title: "타이틀2",
                    contents: "컨텐츠!@!@",
                    date: "2021.03.08",
                },
                {
                    id: 3,
                    title: "타이틀3",
                    contents: "컨텐츠!@!@",
                    date: "2021.03.09",
                },
                {
                    id: 4,
                    title: "타이틀4",
                    contents: "컨텐츠!@!@",
                    date: "2021.03.10",
                },
        ],
    }
    getNotice(){
        axios.get('http://localhost:8000/notice/?page='+this.state.currentPage)
        .then(response => this.setState({
            boardList:response.data
         }));
    }
    getImportant(){
        axios.get('http://localhost:8000/notice/important/')
        .then(response => this.setState({
            importantList:response.data
         }));
    }


    componentDidMount() { //컴포트가 실행될때 처음에 실행되는 함수.
        this.getNotice();
        this.getImportant();
    }

    render(){
        return(
            <div class="Notice">
                <div class="headline">
                    <h2 class="headline-title">공지사항</h2>
                </div>
                {/* 테이블 출력부분 */}
                <div class="board-list">
                        {this.state.importantList.map((item)=>{
                            return(
                                <div class="important">
                                <a id="board-router" href={"/notice/"+item.id}>
                                    <span class="board-id">{item.id}</span>
                                    <span class="board-title">{item.title}</span>
                                    <span class="board-date">{item.date}</span>
                                </a>
                                </div>
                            )
                            })}

                        {this.state.boardList.results.map((item)=>{
                            return(
                                <div>
                                <a id="board-router" href={"/notice/"+item.id}>
                                    <span class="board-id">{item.id}</span>
                                    <span class="board-title">{item.title}</span>
                                    <span class="board-date">{item.date}</span>
                                </a>
                                </div>
                            )
                            })}
                    </div>
                {/* 페이지네이션 */}
                <Pagination
                    pnt={this}
                    currentPage={this.state.currentPage}
                    total={this.state.boardList.count}
                    perPage={15}
                />
            </div>
        )
    }
}
export default Notice;
